Servers: 3
Cpu: "1"
Memory: "512Mi"
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
LogLevel : "DEBUG"
java:
  xmx: -Xmx512m