apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ printf "%s-%s" .Release.Name "zk" | trunc 63 }}
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
spec:
  serviceName: {{ printf "%s-%s" .Release.Name "zk" | trunc 63 }}
  replicas: {{.Values.Servers}}
  template:
    metadata:
      labels:
        component: "{{.Release.Name}}"
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: k8szk
        image: gcr.io/google_samples/k8szk:v2
        ports:
        - containerPort: {{.Values.ClientPort}}
          name: client
        - containerPort: {{.Values.ServerPort}}
          name: server
        - containerPort: {{.Values.LeaderElectionPort}}
          name: leader-election
        env:
        - name : ZK_REPLICAS
          value: "{{.Values.Servers}}"
        - name : ZK_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: jvm.heap
        - name : ZK_TICK_TIME
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: tick
        - name : ZK_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: init
        - name : ZK_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: tick
        - name : ZK_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: client.cnxns
        - name: ZK_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: snap.retain
        - name: ZK_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: purge.interval
        - name: ZK_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "%s-cm-zk" .Release.Name | trunc 24 }}"
                key: log.level
        - name: ZK_CLIENT_PORT
          value: "{{.Values.ClientPort}}"
        - name: ZK_SERVER_PORT
          value: "{{.Values.ServerPort}}"
        - name: ZK_ELECTION_PORT
          value: "{{.Values.LeaderElectionPort}}"
        command:
        - sh
        - -c
        - zkGenConfig.sh && exec zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: {{.Values.ProbeInitialDelaySeconds}}
          timeoutSeconds: {{.Values.ProbeTimeoutSeconds}}
        livenessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: {{.Values.ProbeInitialDelaySeconds}}
          timeoutSeconds: {{.Values.ProbeTimeoutSeconds}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
